apiVersion: v1
kind: Service
metadata:
  name: {{ .Chart.Name }}
  labels:
    {{- include "freo.labels" . | nindent 4 }}
spec:
  type: ClusterIP
  selector:
    {{- include "freo.selectorLabels" . | nindent 4 }}
  ports:
    - name: http
      port: 8080
      targetPort: http
